server:
  port: 7070


spring:
  datasource:
    username: postgres
    password: root
    url: 'jdbc:postgresql://localhost:5432/productDb'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

